### ISSUE TITLE
[QUESTION]In 1.20.4 carpet server fails to start and client cannot be configured using GUI

### ISSUE THREAD

**Issue by Ackerven** [Tslat/TslatEntityStatus#36]
## Problem 1: After adding this mod, the Carpet server cannot be started.

After adding this mod, the server starts and displays the following error:

```text
[00:39:14] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tslatentitystatus'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at net.tslat.tes.networking.TESNetworking.registerPacketInternal(TESNetworking.java:28) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.tslat.tes.core.networking.TESNetworking.registerPacket(TESNetworking.java:106) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.tslat.tes.core.networking.TESNetworking.init(TESNetworking.java:98) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.tslat.tes.TES.onInitialize(TES.java:11) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.tslat.tes.networking.TESNetworking.registerPacketInternal(TESNetworking.java:28) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.tslat.tes.core.networking.TESNetworking.registerPacket(TESNetworking.java:106) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.tslat.tes.core.networking.TESNetworking.init(TESNetworking.java:98) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.tslat.tes.TES.onInitialize(TES.java:11) ~[TES-fabric-1.20.4-1.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 7 more
```
List of mods added to the server:

+ appleskin-fabric-mc1.20.3-2.5.1.jar
+ c2me-fabric-mc1.20.4-0.2.0+alpha.11.65.jar
+ carpet-extra-1.20.3-1.4.128.jar
+ carpet-tis-addition-mc1.20.4-v1.56.1.jar
+ fabric-api-0.96.4+1.20.4.jar
+ fabric-carpet-1.20.3-1.4.128+v231205.jar
+ ferritecore-6.0.3-fabric.jar
+ gugle-carpet-addition-2.7.0-1.20.4.jar
+ lithium-fabric-mc1.20.4-0.12.1.jar
+ magiclib-all-0.7.398+fe2125a-stable.jar
+ malilib-fabric-1.20.4-0.18.1.jar
+ midnightlib-fabric-1.5.3.jar
+ NoChatReports-FABRIC-1.20.4-v2.5.0.jar
+ PluslsCarpetAddition-all-0.3.190+9e97daa-beta.jar
+ servux-fabric-1.20.2-0.1.0.jar
+ spark-1.10.58-fabric.jar
+ starlight-1.1.3+fabric.f5dcd1a.jar
+ TES-fabric-1.20.4-1.5.jar

Is it possible that another mod is causing the conflict? My client also has these mods, but it can start normally.

## Problem 2: MidnightLib has been added to the client, but the GUI configuration button cannot be found in ModMenu

![image](https://github.com/Tslat/TslatEntityStatus/assets/70303900/ac25c558-4fa4-43d5-9bf2-4b22368be3b9)

![image](https://github.com/Tslat/TslatEntityStatus/assets/70303900/39a1dcb2-a3dd-40cd-b06b-cd386adc311a)

**Comment by Tslat** [comment]
Fixed in 1.5.1
